customhost = "employee.cjwcc6ykil89.ap-south-2.rds.amazonaws.com"
customuser = "srinivas" 
custompass = "srinivas2946"
customDb = "employee"
custombucket = "employeebucket"
customregion = "ap-south-2"